version: '3.8'

services:
  redis:
    image: redis:7
    container_name: simple-redis
    volumes:
      - redisdata:/data
    command: ["redis-server", "--save", "60", "1"]
    ports:
      - "6379:6379"

volumes:
  redisdata:
