# docker-compose.yml
version: '3.8'

services:
  app:
    build: ./app
    volumes:
      - logs:/var/log
    ports:
      - "5001:5001"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.20
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.20
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.20
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.20
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - logs:/var/log
    depends_on:
      - logstash

volumes:
  logs:
