name: Project14 - Docker Build and Trivy Scan

on:
  push:
    paths:
      - 'Project14/**'  # Only trigger when files in Project14/ change
    branches: [ main ]
  pull_request:
    paths:
      - 'Project14/**'  # Only trigger on pull requests to main
    branches: [ main ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Project14   # This ensures all steps are executed within the Project14/ directory

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (required for building images in GitHub Actions)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t project14-app:latest .

      # Step 4: Install Trivy (vulnerability scanner)
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      # Step 5: Scan the Docker image using Trivy and save output as JSON
      - name: Scan Docker image with Trivy
        run: |
          trivy image --format json --output trivy-report.json project14-app:latest

      # Step 6: Upload the Trivy scan report as an artifact
      - name: Upload Trivy report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json
